### ISSUE TITLE
unable to parse '<clusterName>' as <project id>_<zone>_<cluster name>

### ISSUE THREAD

**Issue by gregberns** [jenkins-x/terraform-azurerm-jx#21]
## Summary

When the `jx-requirements.yml` file is used to run `jx boot`, a parse error occurs on the `verify-preinstall` command.

```
STEP: verify-preinstall command: /bin/sh -c jx step verify preinstall --provider-values-dir="kubeProviders" in dir: /Users/gb/github/issaonline/gitops-k8s-dev/jenkins-x-boot-config

error: : unable to parse appdevwestus2 as <project id>_<zone>_<cluster name>
error: failed to interpret pipeline file /Users/gb/github/issaonline/gitops-k8s-dev/jenkins-x-boot-config/jenkins-x.yml: failed to run '/bin/sh -c jx step verify preinstall --provider-values-dir="kubeProviders"' command in directory '/Users/gb/github/issaonline/gitops-k8s-dev/jenkins-x-boot-config', output: ''
```

Below are the:

* Input Terraform module configuration
* Resulting `jx-requirements.yml` file
* Output from running `jx boot`

## Module Configuration

Note: I just cloned the current `terraform-azurerm-jx` repo locally to use the module

```tf
# location=uswest2
# environment=dev
variable "location" {
  type        = string
  description = "location of your resource group"
}

variable "environment" {
  type        = string
  description = "runtime environment: prod, dev"
}

module "aks-jx" {
  # source  = "jenkins-x/aks-jx/aks"
  source = "../src/terraform-azurerm-jx/jx_module"
  # version = "1.0.0"

  network_resource_group  = "rg-app-k8s-net-${var.environment}-${var.location}"
  cluster_resource_group  = "rg-app-k8s-clu-${var.environment}-${var.location}"
  dns_resource_group      = "rg-app-k8s-dns-${var.environment}-${var.location}"
  registry_resource_group = "rg-app-k8s-reg-${var.environment}-${var.location}"
  vault_resource_group    = "rg-app-k8s-vau-${var.environment}-${var.location}"

  cluster_name = "app${var.environment}${var.location}"

  create_registry         = true
  container_registry_name = "crappk8s${var.environment}${var.location}"

  # dev_env_approvers = ["gregberns"]

  jenkins_x_namespace = "jx" // default

  location = var.location

  dns_prefix   = "dnsappk8s"
  network_name = "vnet-app-k8s-${var.environment}-${var.location}"

  node_count = 1
  node_size  = "Standard_B2ms"

}
```

## `jx-requirements.yml` File

```
autoUpdate:
  enabled: false
  schedule: ""
cluster:
  clusterName: appdevwestus2
  devEnvApprovers:
  - gregberns
  environmentGitOwner: isaaonline
  gitKind: github
  gitName: github
  gitServer: https://github.com
  namespace: jx
  provider: aks
  registry: crappk8sdevwestus2.azurecr.io
environments:
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: dev
  repository: environment-appdevwestus2-dev
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: staging
  repository: environment-appdevwestus2-staging
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: production
  repository: environment-appdevwestus2-production
gitops: true
ingress:
  domain: tfjxevidentmarlin.
  externalDNS: false
  ignoreLoadBalancer: true
  namespaceSubDomain: -jx.
  tls:
    email: ""
    enabled: false
    production: true
kaniko: true
repository: nexus
secretStorage: vault
storage:
  backup:
    enabled: false
    url: ""
  logs:
    enabled: false
    url: ""
  reports:
    enabled: false
    url: ""
  repository:
    enabled: false
    url: ""
terraform: true
vault: {}
velero:
  schedule: ""
  ttl: ""
versionStream:
  ref: v1.0.571
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: lighthouse
```

## jx boot output

```
jx boot
Creating boot config with defaults, as not in an existing boot directory with a git repository.
No Jenkins X pipeline file jenkins-x.yml or no jx boot requirements file jx-requirements.yml found. You are not running this command from inside a Jenkins X Boot git clone
To continue we will clone https://github.com/jenkins-x/jenkins-x-boot-config.git @ master to jenkins-x-boot-config
? Do you want to clone the Jenkins X Boot Git repository? Yes

Cloning https://github.com/jenkins-x/jenkins-x-boot-config.git @ master to jenkins-x-boot-config
Attempting to resolve version for boot config https://github.com/jenkins-x/jenkins-x-boot-config.git from https://github.com/jenkins-x/jenkins-x-versions.git
Booting Jenkins X

STEP: validate-git command: /bin/sh -c jx step git validate in dir: /Users/gb/github/issaonline/gitops-k8s-dev/jenkins-x-boot-config/env

Git configured for user: Greg Berns and email gregberns@gmail.com

STEP: verify-preinstall command: /bin/sh -c jx step verify preinstall --provider-values-dir="kubeProviders" in dir: /Users/gb/github/issaonline/gitops-k8s-dev/jenkins-x-boot-config

error: : unable to parse appdevwestus2 as <project id>_<zone>_<cluster name>
error: failed to interpret pipeline file /Users/gb/github/issaonline/gitops-k8s-dev/jenkins-x-boot-config/jenkins-x.yml: failed to run '/bin/sh -c jx step verify preinstall --provider-values-dir="kubeProviders"' command in directory '/Users/gb/github/issaonline/gitops-k8s-dev/jenkins-x-boot-config', output: ''
```
