### ISSUE TITLE
Ingress IgnoreLoadBalancer property needs to be set to false 

### ISSUE THREAD

**Issue by gregberns** [jenkins-x/terraform-azurerm-jx#24]
Based on https://github.com/jenkins-x/jx/issues/7537 the Ingress ignoreLoadBalancer property needs to be set to false in the `jx-requirements.yml.tpl` file.

> So, after this PR #7515, we need to set Ingress.IgnoreLoadBalancer in the requirements file to false.

This configuration seems to fix issues standing up the vault:

```
ingress:
  domain: "tfjxevidentmarlin"
  ignoreLoadBalancer: false
  externalDNS: false
  tls:
    email: ""
    enabled: true
    production: true
```
